-- QuikSafe Bot - Optional PostgreSQL RLS Policies
--
-- This project runs with a trusted server-side database role in Coolify,
-- so RLS is not required for baseline operation.
--
-- If you introduce multiple database roles later, you can add RLS policies
-- in this file to enforce table-level access.
